### ISSUE TITLE
target_name is analyzed in provided index template

### ISSUE THREAD

**Issue by mponton** [joshuar/pingbeat#11]
The provided index template for PingBeat has the `target_name` `analyzed` which splits hostnames on dashes (e.g. `abc-xyz.domain.tld` will be split in `abc` and `xyz.domain.tld`). This prevents proper aggregation on hostnames. See:

https://github.com/elastic/elasticsearch/issues/16706

I cannot think of a reason to analyze the `target_name`. Did you have anything in mind?

If not, may I suggest it be changed for others not to run into a similar issue.

Thanks for the great work. I'm actually using your beat as a model for another one I am creating. Your code is very appreciated.

Cheers,

Marco

**Comment by joshuar** [comment]
Hi @mponton,

I'm using the "Logstash" approach for this field.  So  `target_name` is actually a multi-field and there is a  `target_name.raw` field that is not analyzed and can be used for aggregations/filtering.  You can then use `target_name` for searching for all targets that match some string.

Does using `target_name.raw` work for you?  I think this template is up-to-date with both the example dashboard and what I'm currently using :|  If not, I'll update it.

Best regards,

Josh

**Comment by joshuar** [comment]
Closing as I believe this is not an issue and the template has changed a lot now.

**Comment by mponton** [comment]
@joshuar, so sorry not having followed up on this. I somehow missed/forgot your initial reply until I got this close notification. I never tried `target_name.raw` and ended up modifying the index template due to my lack of understanding at the time. The issue was surely 18 inches in front of my screen all that time :-)

Thanks for the great project and your help!

Cheers,

Marco
