### ISSUE TITLE
Index template no longer needed?

### ISSUE THREAD

**Issue by mbadran** [joshuar/pingbeat#15]
Just got this up and running. Very cool :)

One diversion was this comment from the README:

> If intending on using the Elasticsearch output, you should add a new index template using the [supplied one](etc/pingbeat.template.json), for example with:
>
> ```
> curl -XPUT  /_template/pingbeat -d @/path/to/pingbeat.template.json
> ```

Running ```pingbeat``` with the debugger then showed this error:

> 2016/07/02 05:01:19.284452 client.go:173: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"wrong value for index [true] for field [hostname]"}

After deleting the template and the index and running pingbeat again, everything worked fine. It appears that libbeat has changed to use the field mappings from the fields.yml file, correct? If so, the README should probably be updated to avoid confusion.

**Comment by joshuar** [comment]
Thanks for reporting.  I've updated the template which should fix this issue.
