### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by captainark** [joshuar/pingbeat#16]
Hi @joshuar !

I've noticed you've pushed a few changed to the repo, so I figured I'd try and update.

However, it's not working currently. I'm getting the following : 
```
~$ go get -u github.com/joshuar/pingbeat
# cd /opt/go/src/github.com/joshuar/pingbeat; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/github.com/elastic/libbeat'
package github.com/joshuar/pingbeat: exit status 1
```

Thanks !

**Comment by mbadran** [comment]
Run this command in the pingbeat directory:

`git rm --cached vendor/github.com/elastic/libbeat`

Then run go get again. It should work.

**Comment by joshuar** [comment]
Hey @captainark,

Yeah, because I'm using glide, the update/install procedure is a little bit different to standard go practice.

With the latest version, just running `make install` should get you sorted with the `pingbeat` binary in `$GOPATH/bin`.

**Comment by captainark** [comment]
Thanks @joshuar, that fixed it.

I'll have to rewrite my ansible playbook to keep pingbeat updated, but that shouldn't be a problem.
