### ISSUE TITLE
Why is the username/password to elasticsearch deprecated?

### ISSUE THREAD

**Issue by viztastic** [joshuar/pingbeat#19]
Hi,

Reading through the documentation set out [here](https://github.com/joshuar/pingbeat/blob/master/etc/beat.yml) and it says that the username/password fields to elasticsearch are deprecated. Is there a correct way to specify the username/password to elasticsearch?

**Comment by joshuar** [comment]
Ah, this is a relic of back in the old days when Beats first came out and didn't support basic auth. You can ignore this comment, I'll upload a new example file with it removed.  Those parameters work just fine nowadays :)

**Comment by joshuar** [comment]
Closing this as this as this is just bad documentation.
