### ISSUE TITLE
Upgrade libbeat to beats

### ISSUE THREAD

**Issue by DavidJFelix** [joshuar/pingbeat#21]
The libbeat library and sub module you're using have been moved to https://github.com/elastic/beats. I'm opening this issue to track the migration of this code to using the new library location. If I don't hear back in a few days I'll begin work on this.

**Comment by joshuar** [comment]
Hi @DavidJFelix,

Thanks for helping out!  But before you get started, I wanted to double-check if this is needed, as I thought I already switched the repos over?  At least in the current glide.yaml I'm using the right repo:

https://github.com/joshuar/pingbeat/blob/master/glide.yaml#L3

It's possible I'm committing the wrong files to the repo and should be excluding a cache file/directory somewhere that is causing pingbeat to be built against an the old beats repo.  I'm pretty much learning  the Glide stuff as I go :)

Best regards,

Josh

**Comment by DavidJFelix** [comment]
@joshuar ah, you're right. Yeah -- the README threw me off. I'll fix that real quick.
