### ISSUE TITLE
Don't require glide for make; vendor dependencies

### ISSUE THREAD

**Issue by DavidJFelix** [joshuar/pingbeat#23]
Hey, sorry for all of the attention on this lately. I started using this and wanted to give back a bit where possible.

I wanted to open this issue to start a discussion about the use of [vendoring](https://golang.org/cmd/go/#hdr-Vendor_Directories) in this repo. So the idea behind vendoring is that for almost all cases in go repos, a users should be able to `git pull` or `go get` a repo and build it for their machine using `go build` or `go install` exclusively. This helps reduce tooling fatigue and "keep it simple". The issue is that if a library isn't living constantly on the bleeding edge of its dependencies, you could get build inconsistencies using go exclusively. That's where tools like glide come in.

Glide is really great for dependency management, and using it with check-in vendoring means only people upgrading dependencies need to have it installed. 

My proposal is 3(4) fold:
- Modifications to the Makefile to _not_ depend on glide and possibly focus the make targets
- Utilize vendoring and check in dependencies to keep all dependent source in this repo
- Change documentation to encourage use of `go build` exclusively for building a binary for the system being built on
- (4th) This may open opportunities in the CI build to reduce complexity.

Let me know what you think. If you want to see what some of these changes might look like, I can get some PR together to show what I mean.

**Comment by joshuar** [comment]
Hi @DavidJFelix sorry for not replying on this issue for like, ages :'(

Yeah I'd be happy to explore some of these ideas.  I'm a complete n00b for this kind of stuff.  Glide was something the *beats tools originally used, and I seemed to be able to grok enough of it to get it working with Pingbeat.  Certainly the tooling around Go vendoring and deps is improving to the point Glide might be unnecessary?
