### ISSUE TITLE
target_name.raw is not getting data anymore

### ISSUE THREAD

**Issue by raz3k** [joshuar/pingbeat#27]
Just build the master release and now i don't get the dns in target_name.raw anymore, only in target_name which is analyzed and can't be used. how can i fix this ?

Also the predefined dashboards aren't available anymore.

Thanks.

**Comment by joshuar** [comment]
Hi @raz3k, I'm still in the process of making some changes in pingbeat that will break a few things.  I'd recommend sticking to the [last release](https://github.com/joshuar/pingbeat/releases/tag/1.0-beta1) for usage until I spin a new one and update the docs.
