### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Noebas** [joshuar/pingbeat#5]
So far so good, only getting this error.

Any ideas on what this could be?

2015/11/09 09:38:52.572100 preprocess.go:42: ERR Publishing event failed: Missin
g '@timestamp' field from event

**Comment by ruflin** [comment]
@joshuar @Noebas This is related to the most recent changes in libbeat. We renamed timestamp to @timestamp You have to adjust this line here and make it @timestamp: https://github.com/joshuar/pingbeat/blob/master/pingbeat.go#L151

**Comment by Noebas** [comment]
That solved it, running perfect. I am now going to test with 200+ targets and making a dashboard :)

**Comment by joshuar** [comment]
Fixed!
