### ISSUE TITLE
Installation instructions for Logstash 2.1

### ISSUE THREAD

**Issue by bigtoerag** [joshuar/pingbeat#8]
Would you be able to update the installation info to outline how a non-developer could get this running (possible ./pluign method).  
The go command doesn't seem to do anything descernable on my ubuntu box and not sure where it needs to be run and what needs to be done running the command.

 I have a customer demo this would be excellent for along side packetbeat, topbeat and filebeat.

**Comment by bigtoerag** [comment]
Here is the failure I get:

		root@linux:/usr/lib/go/pingbeat# go get -u github.com/joshuar/pingbeat
		# github.com/elastic/libbeat/logp
		/root/go/src/github.com/elastic/libbeat/logp/log.go:145:59: error: reference to undefined identifier ‘log.LUTC’
		   flag := log.Ldate | log.Ltime | log.Lmicroseconds | log.LUTC | log.Lshortfile
																   ^
		# golang.org/x/net/ipv6
		/root/go/src/golang.org/x/net/ipv6/thunk_linux_386.s: Assembler messages:
		/root/go/src/golang.org/x/net/ipv6/thunk_linux_386.s:7: Error: no such instruction: `text ·socketcall(SB),4,$0-36'
		/root/go/src/golang.org/x/net/ipv6/thunk_linux_386.s:8: Error: junk `(SB)' after expression
		# golang.org/x/net/ipv4
		/root/go/src/golang.org/x/net/ipv4/thunk_linux_386.s: Assembler messages:
		/root/go/src/golang.org/x/net/ipv4/thunk_linux_386.s:7: Error: no such instruction: `text ·socketcall(SB),4,$0-36'
		/root/go/src/golang.org/x/net/ipv4/thunk_linux_386.s:8: Error: junk `(SB)' after expression

**Comment by joshuar** [comment]
Hi @bigtoerag, it looks like you are using gccgo (Ubuntu package **gccgo**).  Can you install the **golang** package instead and use the Go compiler provided by that?  libbeat requires Go 1.5+ and I don't think gccgo supports it. You'll need to run `go clean` before `go build` after installing the different Go compiler.

**Comment by bigtoerag** [comment]
You can close now as it must environmental for me.  I had a colleague try and now have a binary running.  Thanks for the help and keep it up.
